_wandb:
    value:
        cli_version: 0.22.3
        e:
            5thc6xhfjiqeeuhyx7boey98aj3p5dhz:
                apple:
                    ecpuCores: 6
                    gpuCores: 14
                    memoryGb: 18
                    name: Apple M3 Pro
                    pcpuCores: 5
                    ramTotalBytes: "19327352832"
                codePath: /Users/amalahmadinurov/Desktop/Subjects_ZS_2025/ZNEUS/zneus-project-1/model-binary.ipynb
                codePathLocal: model-binary.ipynb
                cpu_count: 11
                cpu_count_logical: 11
                disk:
                    /:
                        total: "494384795648"
                        used: "433084395520"
                email: amal.akhmadinurov@gmail.com
                executable: /Users/amalahmadinurov/Desktop/Subjects_ZS_2025/ZNEUS/zneus-project-1/.venv/bin/python
                git:
                    commit: 706b4ad5b9401b2ad1acd1151140c3d7a50fd317
                    remote: https://github.com/AmalAkh/zneus-project-1
                host: Amals-MBP
                memory:
                    total: "19327352832"
                os: macOS-26.0.1-arm64-arm-64bit-Mach-O
                program: /Users/amalahmadinurov/Desktop/Subjects_ZS_2025/ZNEUS/zneus-project-1/model-binary.ipynb
                python: CPython 3.13.7
                root: /Users/amalahmadinurov/Desktop/Subjects_ZS_2025/ZNEUS/zneus-project-1
                startedAt: "2025-11-08T17:14:41.381268Z"
                writerId: 5thc6xhfjiqeeuhyx7boey98aj3p5dhz
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 19
            "4": 3.13.7
            "5": 0.22.3
            "8":
                - 1
            "12": 0.22.3
            "13": darwin-arm64
batch_size:
    value: 32
desc:
    value: 'MLP: (512, ReLU) (256, ReLU) (1)'
early_stopping_patience:
    value: 10
learning_rate:
    value: 0.001
loss_function:
    value: BinaryCrossentropy with logits
max_epochs:
    value: 50
reduce_lr_patience:
    value: 10
